#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-decorator
Version  : 5.1.1
Release  : 97
URL      : https://files.pythonhosted.org/packages/66/0c/8d907af351aa16b42caae42f9d6aa37b900c67308052d10fdce809f8d952/decorator-5.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/66/0c/8d907af351aa16b42caae42f9d6aa37b900c67308052d10fdce809f8d952/decorator-5.1.1.tar.gz
Summary  : Decorators for Humans
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-decorator-license = %{version}-%{release}
Requires: pypi-decorator-python = %{version}-%{release}
Requires: pypi-decorator-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=====================
        
        The goal of the decorator module is to make it easy to define
        signature-preserving function decorators and decorator factories.
        It also includes an implementation of multiple dispatch and other niceties
        (please check the docs). It is released under a two-clauses
        BSD license, i.e. basically you can do whatever you want with it but I am not
        responsible.
        
        Installation
        -------------
        
        If you are lazy, just perform
        
         ``$ pip install decorator``
        
        which will install just the module on your system.
        
        If you prefer to install the full distribution from source, including
        the documentation, clone the `GitHub repo`_ or download the tarball_, unpack it and run
        
         ``$ pip install .``
        
        in the main directory, possibly as superuser.

%package license
Summary: license components for the pypi-decorator package.
Group: Default

%description license
license components for the pypi-decorator package.


%package python
Summary: python components for the pypi-decorator package.
Group: Default
Requires: pypi-decorator-python3 = %{version}-%{release}

%description python
python components for the pypi-decorator package.


%package python3
Summary: python3 components for the pypi-decorator package.
Group: Default
Requires: python3-core
Provides: pypi(decorator)

%description python3
python3 components for the pypi-decorator package.


%prep
%setup -q -n decorator-5.1.1
cd %{_builddir}/decorator-5.1.1
pushd ..
cp -a decorator-5.1.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672267147
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-decorator
cp %{_builddir}/decorator-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-decorator/3483701a3a93cfae3581f5a544e3a21fe01933bc || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-decorator/3483701a3a93cfae3581f5a544e3a21fe01933bc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
